apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: pvc-gluster-heketi
spec:
   storageClassName: gluster-heketi
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 1GB