apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: weblogiclogs
spec:
   accessModes:
   - ReadWriteOnce
resources:
   requests:
      storage: 5GB
volumes:
   - name: mypd
      persistentVolumeClaim:
         claimName: weblogiclogs