apiVersion: v1
kind: PersistentVolume
metadata:
   name: data-nfsplugin
   labels:
      name: data-nfsplugin
   annotations:
      csi.volume.kubernetes.io/volume-attributes: '{"server": "192.168.10.4", "share" "/nfs"}'
spec:
   accessModes:
   - ReadWriteOnce
   capacity:
      storage: 100MB
   csi:
      driver: csi-nfsplugin
      volumeHandle: data-id