apiVersion: v1
kind: PersistentVolume
metadata:
   name: v1
   labels:
      type: nfs
spec:
   capacity:
      storage: 5GB
   accessModes:
      - ReadWriteOnce
   persistentVolumeReclaimPolicy: Recycle
   storageClassName: nfs
   nfs:
      path: /tmp
      server: 172.17.0.2