apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv0003
spec:
   capacity:
      storage: 5GB
   accessModes:
      - ReadWriteOnce
   persistentVolumeReclaimPolicy: Recycle
   nfs:
      path: /k8s/weblogic
      server: 192.168.0.103