apiVersion: v1
kind: ServiceMonitor
metadata:
   name: kube-state-metrics
   labels:
      team: frontend
   spec:
      jobLabel: k8s-app
      selector:
         matchLabels:
            k8s-app: kube-state-metrics
      namespaceSelector:
         any: true
      endpoint:
      - port: http-metrics
        scheme: http