apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
   name: example-app
   labels:
      team: fronted
spec:
   selector:
      matchLabels:
         app: example-app
   endpoints:
   - port: web