apiVersion: v1
kind: ResourceQuota
metadata:
   name: compute-resources
   namespace: default
spec:
   hard:
      requests.cpu: "1"
      requests.memory: 1GB
      limits.cpu: "2"
      limits.memory: 2GB
      pods: "4"
      configmaps: "10"
      persistentvolumeclaims: "4"
      replicationcontrollers: "20"
      secrets: "10"
      services: "10"
      services.loadbalancers: "2"